/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "spr"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Glenn Hickey hickey@cs.dal.ca"

/* Define to the full name of this package. */
#define PACKAGE_NAME "spr"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "spr 0.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "spr"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.1"

/* Version number of package */
#define VERSION "0.0.1"
